### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'num_points'

### ISSUE THREAD

**Issue by 3bobo** [fxia22/pointnet.pytorch#24]
when I run `train_classification.py`, there is an error:
```
Traceback (most recent call last):
  File "train_classification.py", line 58, in <module>
    classifier = PointNetCls(k = num_classes, num_points = opt.num_points)
TypeError: __init__() got an unexpected keyword argument 'num_points'
```
I noticed that `opt.num_points` has been used in 
https://github.com/fxia22/pointnet.pytorch/blob/2ec315f174ed5ffc05d127d5cf14c94ce873c1e0/train_classification.py#L40
so I comment it and run again, but another error:
`ValueError: Expected more than 1 value per channel when training, got input size [1, 512]`
and this comes from :
https://github.com/fxia22/pointnet.pytorch/blob/2ec315f174ed5ffc05d127d5cf14c94ce873c1e0/pointnet.py#L47
how to solve it? thanks for your help

**Comment by mayurbhangale** [comment]
Seems like `num_points` is never used in `PointNetCls`. I solved it by simply not passing it on line 58 `classifier = PointNetCls(k = num_classes)`.

**Comment by 3bobo** [comment]
@mayurbhangale thanks for your help, I've changed this line, but I still get the error:
`ValueError: Expected more than 1 value per channel when training, got input size [1, 512]`, which is caused by `bathnorm1d ` from pytorch, so I change this line:
https://github.com/fxia22/pointnet.pytorch/blob/2ec315f174ed5ffc05d127d5cf14c94ce873c1e0/pointnet.py#L47
to:
`x = F.relu(self.fc1(x))`
but this time all output data are zero, like [this,](https://github.com/fxia22/pointnet.pytorch/issues/11)   have you met this?

**Comment by mayurbhangale** [comment]
Not really,
In fact, I've successfully trained classification and segmentation. Sharing weights: https://drive.google.com/open?id=16fXGyOTOxvT-ozYwu3OPL3Qk4vaS6liL

**Comment by 3bobo** [comment]
@mayurbhangale ,thanks for sharing your weights, I will try to test and see the result , but I'm still wondering what's wrong with mine, it will be convenient for further our using.

**Comment by DC1991** [comment]
Hi @mayurbhangale , how about your test performance on your trained classification model. I tested the trained model (25 epochs, on classification), the accuracy is always 0.0000000 and the loss is about 1.5-2.0.

**Comment by alfredtorres** [comment]
> Hi @mayurbhangale , how about your test performance on your trained classification model. I tested the trained model (25 epochs, on classification), the accuracy is always 0.0000000 and the loss is about 1.5-2.0.

you just run the show_cls.py ? maybe the last line in this .py has something run, the loss around 1.5-2 may be ok.
I try 60 epochs ,get nearly 95% acc.
