### ISSUE TITLE
modelnet40 data download and preprocessing

### ISSUE THREAD

**Issue by linhaojia13** [fxia22/pointnet.pytorch#35]
When I run the  download.sh, I only get a subset of shapenet. Does it means that I need to download the modelnet40 myself?

**Comment by fxia22** [comment]
Yes, you need to download modelnet40 and prepare the data yourself. The data processing pipeline include sampling enough points on the mesh and saving them into ply files. I have a processed version but I am not able to host it for distribution.

The folder structure looks like the following:

```
.
├── airplane
│   ├── test [100 entries exceeds filelimit, not opening dir]
│   └── train [626 entries exceeds filelimit, not opening dir]
├── bathtub
│   ├── test [50 entries exceeds filelimit, not opening dir]
│   └── train [106 entries exceeds filelimit, not opening dir]
├── bed
│   ├── test [100 entries exceeds filelimit, not opening dir]
│   └── train [515 entries exceeds filelimit, not opening dir]
```

**Comment by linhaojia13** [comment]
Thank you for your reply. I have decided to turn to another way to finish my task in which I don't need a pytorch version of pointnet. Thank you anyway!

**Comment by neverstoplearn** [comment]
> Yes, you need to download modelnet40 and prepare the data yourself. The data processing pipeline include sampling enough points on the mesh and saving them into ply files. I have a processed version but I am not able to host it for distribution.
> 
> The folder structure looks like the following:
> 
> ```
> .
> ├── airplane
> │   ├── test [100 entries exceeds filelimit, not opening dir]
> │   └── train [626 entries exceeds filelimit, not opening dir]
> ├── bathtub
> │   ├── test [50 entries exceeds filelimit, not opening dir]
> │   └── train [106 entries exceeds filelimit, not opening dir]
> ├── bed
> │   ├── test [100 entries exceeds filelimit, not opening dir]
> │   └── train [515 entries exceeds filelimit, not opening dir]
> ```

How should i process it to meet the code? thanks
