### ISSUE TITLE
why need install pointnet,it is tools?

### ISSUE THREAD

**Issue by XGuider** [fxia22/pointnet.pytorch#43]

**Comment by NhanTran96** [comment]
PointNet is basically implemented as a Python class. Hence, there's no need to install it.
Though to train it you are required to install some dependencies as specified in the **setup.py** file:

```
      install_requires=['torch',
                        'tqdm',
                        'plyfile'],
```

**Comment by XGuider** [comment]
thank you so much!!! i get .




------------------ 原始邮件 ------------------
发件人: "Nhan"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 下午3:24
收件人: "fxia22/pointnet.pytorch"<pointnet.pytorch@noreply.github.com>;
抄送: "Xslience"<973279990@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fxia22/pointnet.pytorch] why need install pointnet,it is tools?(#43)




PointNet is basically implemented as a Python class. Hence, there's no need to install it.
 Though to train it you are required to install some dependencies as specified in the setup.py file:
       install_requires=['torch',                         'tqdm',                         'plyfile'],

**Comment by NhanTran96** [comment]
> thank you so much!!! i get .

If everything is resolved, you can close this issue.
