### ISSUE TITLE
where is the trainval.txt？？

### ISSUE THREAD

**Issue by York1996OutLook** [fxia22/pointnet.pytorch#50]
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/ModelNet40/trainval.txt'

**Comment by fxia22** [comment]
[trainval.txt](https://github.com/fxia22/pointnet.pytorch/files/3659189/trainval.txt)

**Comment by fxia22** [comment]
#52

**Comment by sunjunling666** [comment]
trainval.txt what is it?

**Comment by sunjunling666** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\PointNet\\pointnet.pytorch-master\\data\\modelnet40_normal_resampled\\test.txt'
