### ISSUE TITLE
View Segementation Results

### ISSUE THREAD

**Issue by dhirajsuvarna** [fxia22/pointnet.pytorch#60]
Hi @fxia22,

I would like to know, if `train_segmentation.py` generates the segemented point cloud, since it would be good to view a segmented point cloud. 

In addition to that, it would also be helpful to view the critical point and the upper bound shapes as mentioned in the pointnet paper. Do let me know your views.

**Comment by fxia22** [comment]
Yes, `train_segmentation.py ` generates segmented point cloud, and sample results is shown in README.

**Comment by dhirajsuvarna** [comment]
@fxia22, Thanks I figured it out and implemented the same :)
