### ISSUE TITLE
IndexError: trying to index 3 dimensions of a 2 dimensional tensor

### ISSUE THREAD

**Issue by zhangguanghui1** [fxia22/pointnet.pytorch#7]
The error occurs , when I run the last command:  python show_seg.py --model seg/seg_model_20.pth, thanks so much , please

**Comment by tejaskhot** [comment]
I am getting the same error.

**Comment by fxia22** [comment]
noted, might be a pytorch version incompatibility issue.

**Comment by tejaskhot** [comment]
@zhangguanghui1 This can be fixed by changing the following line in `show_seg.py`
`pred_choice = pred.data.max(2)[1][0,:,0]`
to
`pred_choice = pred.data.max(2)[1]`

**Comment by zhangguanghui1** [comment]
@tejaskhot Thanks a lot!
