### ISSUE TITLE
Architecture: Very small issue 

### ISSUE THREAD

**Issue by timothylimyl** [fxia22/pointnet.pytorch#80]
Hi Fei Xia,

I was wondering whether this line (`14-15`) of code in the PointNet Architecture is missing an extra layer as of the official paper release:

```
class STN3d(nn.Module):
    def __init__(self):
        super(STN3d, self).__init__()
        self.conv1 = torch.nn.Conv1d(3, 64, 1)
        *---HERE-> = torch.nn.Conv1d(64,64,1)*
        self.conv2 = torch.nn.Conv1d(64, 128, 1)

```

Not a very big deal but just want to clarify on this.

Cheers,
Tim

**Comment by chrispduck** [comment]
I believe this layer is missing - see line 33 of original TensorFlow implementation [here](https://github.com/charlesq34/pointnet/blob/master/models/pointnet_cls.py)

**Comment by janotjir** [comment]
Yes, I think it is missing too. But if I got it right, instead in STN3d (T-Net) architecture, which consists of MLP(64, 128, 1024), I would add it to the class PointNetfeat
