### ISSUE TITLE
pointnet++

### ISSUE THREAD

**Issue by manuel-delverme** [fxia22/pointnet.pytorch#9]
Do you have any plan to port pointnet++ to pytorch?
if so, I could help :)

**Comment by fxia22** [comment]
yeah, that's on my list. Thanks you. ;P

**Comment by manuel-delverme** [comment]
are you open to collaborations? we risk ending up implementing the same code :thumbsdown:

**Comment by fxia22** [comment]
yeah, I am definitely open to collaborations, feel free to open a repo and invite me in. :)

**Comment by tejaskhot** [comment]
Just to confirm, is this pointnet2 pytorch implementation not complete? Or do you propose to make any additions?
https://github.com/eriche2016/pointnet2.pytorch

**Comment by manuel-delverme** [comment]
that looks like pointnet1.2, but that's not the repo anyway
https://github.com/manuel-delverme/pointnet2.pytorch/ is the empty repo for now

**Comment by fxia22** [comment]
re @tejaskhot That is a pointnet implementation not pointnet++
Thanks @manuel-delverme for creating the new repo!

**Comment by tejaskhot** [comment]
@manuel-delverme Do you have an estimated release date for the code?
